clear
echo "                  "
echo "          /\      "
echo "         |/\|     "
echo "         /  \     "
echo "        / () \    "
echo "       /|    |\   "
echo "      | | /\ | |	"
echo "      | ||  || |	"
echo "      | |\__/| |	"
echo "      \ \    / /	"
echo "       \ \__/ /	"
echo "        \    /	"
echo "         \  /	"
echo "          \/	"
sleep 1
clear
echo "                  "
echo "          /\      "
echo "         |/\|     "
echo "         /  \     "
echo "        / () \    "
echo "       /|    |\   "
echo "      | | /\ | |	"
echo "      | ||  || |	"
echo "      | |\_@/| |	"
echo "      \ \    / /	"
echo "       \ \__/ /	"
echo "        \    /	"
echo "         \  /	"
echo "          \/	"
sleep 1
clear
echo "                  "
echo "          /\      "
echo "         |/\|     "
echo "         /  \     "
echo "        / () \    "
echo "       /|    |\   "
echo "      | | /\ | |	"
echo "      | ||  || |	"
echo "      | |\a@/| |	"
echo "      \ \  a / /	"
echo "       \ \__/ /	"
echo "        \    /	"
echo "         \  /	"
echo "          \/	"
sleep 1
clear
echo "                  "
echo "          /\      "
echo "         |/\|     "
echo "         /  \     "
echo "        / () \    "
echo "       /|    |\   "
echo "      | | /\ | |	"
echo "      | ||  || |	"
echo "      | |\@@/| |	"
echo "      \ \ a@ / /	"
echo "       \ \_a/ /	"
echo "        \    /	"
echo "         \  /	"
echo "          \/	"
