clear
echo "                                   "
echo "          /\                       "
echo "         |/\|                      "
echo "         /  \                      "
echo "        / () \               _     "
echo "       /|    |\             / \    "
echo "      | | /\ | |           |  O|   "
echo "      | ||  || |            \_/    "
echo "      | |\__/| |	                 "
echo "      \ \    / /          @        "
echo "       \ \__/ /          /         "
echo "        \    /	                 "
echo "         \  /	                 "
echo "          \/	                 "
sleep 1
clear
echo "                                   "
echo "          /\                       "
echo "         |/\|                      "
echo "         /  \                      "
echo "        / () \               _     "
echo "       /|    |\             / \    "
echo "      | | /\ | |           |  O|   "
echo "      | ||  || |            \_/    "
echo "      | |\_@/| |           @       "
echo "      \ \    / /          /        "
echo "       \ \__/ /	                 "
echo "        \    /	                 "
echo "         \  /	                 "
echo "          \/	                 "
sleep 1
clear
echo "                                   "
echo "          /\                       "
echo "         |/\|                      "
echo "         /  \                      "
echo "        / () \               _     "
echo "       /|    |\             / \    "
echo "      | | /\ | |           | O |   "
echo "      | ||  || |            @_/    "
echo "      | |\a@/| |           /       "
echo "      \ \  a / /	                 "
echo "       \ \__/ /	                 "
echo "        \    /	                 "
echo "         \  /	                 "
echo "          \/	                 "
sleep 1
clear
echo "                                   "
echo "          /\               /\/\    "
echo "         |/\|              \  /    "
echo "         /  \               \/  !  "
echo "        / () \               _     "
echo "       /|    |\             /_\    "
echo "      | | /\ | |           ||@l|   "
echo "      | ||  || |            \_/    "
echo "      | |\@@/| |	                 "
echo "      \ \ a@ / /	                 "
echo "       \ \_a/ /	                 "
echo "        \    /	                 "
echo "         \  /	                 "
echo "          \/	                 "
