clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            | /                |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||/               \|                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 }                            "
echo "                           |            | \               /|                            "
echo "                           |            | |\_____________/ |                            "
echo "                           |            | | /'''/          |                            "
echo "                           |            | |/   /           |                            "
echo "                          /            \|_/   /            /                            "
echo "                          |                  /                                          "
echo "                          |                  \                                          "
echo "                          |            |\    /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            |                                               "
echo "                           |            |/                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||/               \|                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 }                            "
echo "                           |            | \               /|                            "
echo "                           |            | |\_____________/ |                            "
echo "                           |            | |/   /           |                            "
echo "                          /            \|_/   /            |                            "
echo "                          |                  /             /                            "
echo "                          |                  \                                          "
echo "                          |            |\    /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
