clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            |                                               "
echo "                           |            |/                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||/               \|             _              "
echo "                           |            ||                 |            / \             "
echo "                           |            ||                 |           |  O|            "
echo "                           |            ||                 |            \_/             "
echo "                           |            ||                 }                            "
echo "                           |            | \               /|          @                 "
echo "                           |            | |\_____________/ |         /                  "
echo "                           |            | |/   /           |                            "
echo "                          /            \|_/   /            |                            "
echo "                          |                  /             /                            "
echo "                          |                  \                                          "
echo "                          |            |\    /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            |                                               "
echo "                           |            |/                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||/               \|             _              "
echo "                           |            ||                 |            / \             "
echo "                           |            ||                 |           |  O|            "
echo "                           |            ||                 |            \_/             "
echo "                           |            ||                 }           @                "
echo "                           |            | \               /|          /                 "
echo "                           |            | |\_____________/ |                            "
echo "                           |            | |/   /           |                            "
echo "                          /            \|_/ @ /            |                            "
echo "                          |                  /             /                            "
echo "                          |                  \@                                         "
echo "                          |            |\@   /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            |                                               "
echo "                           |            |/                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||                 |                            "
echo "                           |            ||/               \|             _              "
echo "                           |            ||                 |            / \             "
echo "                           |            ||                 |           | O |            "
echo "                           |            ||                 |            @_/             "
echo "                           |            ||                 }           /                "
echo "                           |            | \               /|                            "
echo "                           |            | |\_____________/ |                            "
echo "                           |            | |/@a /           |                            "
echo "                          /            \|_/ a /            |                            "
echo "                          |                  /             /                            "
echo "                          |                  \                                          "
echo "                          |            |\    /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
clear
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                           |            |                                               "
echo "                           |            |/                 |           /\/\             "
echo "                           |            ||                 |           \  /             "
echo "                           |            ||                 |            \/  !           "
echo "                           |            ||/               \|             _              "
echo "                           |            ||                 |            /_\             "
echo "                           |            ||                 |           ||@l|            "
echo "                           |            ||                 |            \_/             "
echo "                           |            ||                 }                            "
echo "                           |            | \               /|                            "
echo "                           |            | |\_____________/ |                            "
echo "                           |            | |/@@ /           |                            "
echo "                          /            \|_/ @a/            |                            "
echo "                          |                 a/             /                            "
echo "                          |                  \                                          "
echo "                          |            |\    /                                          "
echo "                          \            / \__/                                           "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
echo "                                                                                        "
sleep 1
